name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.18
          
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Run lint check
        run: bun run lint:check
